version: '3.5'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.app
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 4000:4000
    depends_on:
      - postgres
    restart: always
    networks:
      - db_app_bridge

  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      - POSTGRES_PASSWORD=postgres
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-logs:/var/log/postgresql
    ports:
      - '5433:5432'
    restart: always
    networks:
      - db_app_bridge

volumes:
  db-data:
  db-logs:


networks:
  db_app_bridge:
    driver: bridge
